task_manager/apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from apps.users import views
from .views import CustomLoginView
from .views import user_profile, CustomPasswordChangeView

urlpatterns = [
    # path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/login.html') , name='login'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(next_page='next'), name='logout'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='login'),
         name='logout'),  # Cambia 'next' a 'login'
    path('accounts/register/', views.register, name='register'),
    path('profile/', user_profile, name='profile'),
    path('change-password/', CustomPasswordChangeView.as_view(),
         name='change_password'),

    path('users/', views.user_list, name='user_list'),
    path('users/create/', views.user_create, name='user_create'),
    path('users/<int:user_id>/', views.user_detail, name='user_detail'),
    path('users/edit/<int:user_id>/', views.user_edit, name='user_edit'),
    path('users/delete/<int:user_id>/', views.user_delete, name='user_delete'),
    path('users/reactivate/<int:user_id>/', views.user_reactivate, name='user_reactivate'),


    path('customers/', views.customer_list.as_view(), name='customer_list'),
    path('customers/create/', views.customer_create.as_view(),
         name='customer_create'),
    path('customers/edit/<int:pk>/',
         views.customer_update.as_view(), name='customer_edit'),
    path('customers/delete/<int:pk>/',
         views.customer_delete.as_view(), name='customer_delete'),


    #urls version api
    path('users/list_api/', views.user_list_api, name='user_list_api'),
    path('users/edit_api/<int:pk>/', views.user_edit_api, name='user_edit_api'),
    path('users/detail_api/<int:pk>/', views.user_detail_api, name='user_detail_api'),
    path('users/delete_api/', views.user_delete_api, name='user_delete_api'),
    path('users/reactivate_api/', views.user_reactivate_api, name='user_reactivate_api'),


    path('customers/list_api/', views.customer_list_api, name='customer_list_api'),
    path('customers/detail_api/<int:pk>/', views.customer_detail_api, name='customer_detail_api'),






]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework.documentation import include_docs_urls



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.tasks.urls')),
    path('', include('apps.users.urls')),
    path('api/v1/', include('apps.api.urls')),
    path('docs/',include_docs_urls(title='Api Documentation'))


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/tasks/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='tasks/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.task_list, name='task_list'),
    path('task/new/', views.task_create, name='task_create'),
    path('task/<int:pk>/delete/', views.task_delete, name='task_delete'),
    path('task/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/edit/<int:pk>/', views.task_edit, name='task_edit'),
    path('register/', views.register, name='register'),
]

task_manager/apps/users/models.py
import re
from django.core.exceptions import ValidationError
from django.db import models
from phone_field import PhoneField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin, Group, Permission
from django.utils import timezone
from datetime import date, datetime, timedelta
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

"""
phone_regex = RegexValidator(
    regex=r'^\+?1?\d{1,10}$',
    message="El número de teléfono debe ingresarse en el formato: '+999999999'. Hasta 10 dígitos permitidos."
)
"""


# Create your models here.
class UserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        user = self.model(email=self.normalize_email(email),
                          is_active=True,
                          is_staff=is_staff,
                          is_superuser=is_superuser,
                          last_login=timezone.now(),
                          created=timezone.now(),
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        is_staff = extra_fields.pop('is_staff', True)
        is_superuser = extra_fields.pop('is_superuser', False)
        return self._create_user(email, password, is_staff, is_superuser, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, is_staff=True, is_superuser=True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(verbose_name="Nombres", max_length=255)
    lastname = models.CharField(verbose_name="Apellidos", max_length=255)
    document = models.CharField(
        verbose_name='Documento', max_length=30, blank=True, null=True)
    email = models.EmailField(
        verbose_name='Correo Electrónico', unique=True, max_length=255)
    phone = PhoneField(blank=True, help_text='Teléfono/Celular')
    avatar = models.ImageField(
        verbose_name='Foto Perfil', upload_to='user_profile/', blank=True, null=True)
    is_admin = models.BooleanField(verbose_name='Admin', default=False)
    is_active = models.BooleanField(
        verbose_name='Activo/Inactivo', default=True)
    is_staff = models.BooleanField(verbose_name='Permiso al PA', default=False)
    # Nuevo campo para habilitar/deshabilitar
    enabled = models.BooleanField(default=True)
    groups = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, verbose_name="Grupo", help_text=(
        'The groups this user belongs to. A user will get all permissions granted to each of their groups.'))

    def save(self, *args, **kwargs):
        # Llama al método save de la clase base
        super(User, self).save(*args, **kwargs)

        # Crea un token para el usuario si es nuevo
        if not Token.objects.filter(user=self).exists():
            Token.objects.create(user=self)

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_set',  # Nombre único para evitar el choque
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='Grupo',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        # Nombre único para evitar el choque
        related_name='custom_user_set_permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='Permiso de Usuario',
    )
    created = models.DateTimeField(verbose_name='Creada el', auto_now_add=True,
                                   blank=True, null=True, help_text='La fecha de creacion de este objeto')
    modified = models.DateTimeField(verbose_name='Modificada el', auto_now=True,
                                    blank=True, null=True, help_text='la fecha de modificacion de este objeto')

    # Fields settings
    REQUIRED_FIELDS = []  # removes email from REQUIRED_FIELDS
    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def __str__(self):
        if self.document:
            return self.name + " " + self.lastname+" - "+self.document
        else:
            return self.name + " " + self.lastname

    def name_complete(self):
        return self.name + " " + self.lastname

    def name_short(self):
        print(f"Nombre completo: {self.name_complete()}")  # Para depuración
        # names = (self.name).split()[0] +" "+ (self.lastname).split()[0]  # Suponiendo que 'name' es un campo que contiene el nombre completo.
        names = self.name.split()
        if names:
            return names[0]
        return "nombre no disponible"


class UtilsData(models.Model):
    created = models.DateTimeField(
        'creada el',
        auto_now_add=True,
        blank=True,
        null=True,
        help_text='La fecha de creacion de este objeto',
    )
    modified = models.DateTimeField(
        'modificada el',
        auto_now=True,
        help_text='la fecha de modificacion de este objeto',
    )
    enable = models.BooleanField("Visible/No Visible", default=True)
    user = models.ForeignKey(User, verbose_name="Creado por",
                             on_delete=models.SET_NULL, blank=True, null=True)


class Customer(UtilsData):
    name = models.CharField(
        verbose_name="Nombre / Razon social", max_length=255)
    email = models.EmailField(verbose_name="Correo", max_length=254)
    phone = PhoneField(blank=True, help_text='Teléfono/Celular')

task_manager/apps/users/forms.py
from django.core.exceptions import ValidationError
from .models import Customer
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from .models import User
import re
from django.contrib.auth.models import Group





class UserForm(forms.ModelForm):
    # Campos específicos del formulario
    phone = forms.CharField(
        required=False,
        help_text='Teléfono/Celular',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su teléfono'})
    )
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        label='Grupos',
        help_text='Seleccione los grupos a los que pertenece el usuario'
    )

    class Meta:
        model = User
        fields = ['name', 'lastname', 'email', 'phone', 'avatar', 'is_staff', 'is_admin', 'enabled', 'groups']
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese nombre'
            }),
            'lastname': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese apellidos'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ingrese su correo electrónico'
            }),
            'avatar': forms.FileInput(attrs={
                'class': 'form-control-file'
            }),
            'is_staff': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            }),
            'is_admin': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            }),
            'enabled': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            }),
        }





class EmailAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label='Correo Electrónico', max_length=254)

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        User = get_user_model()

        # Asegúrate de que el usuario exista
        if email and password:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                raise forms.ValidationError('Usuario no encontrado.')

            # Verifica la contraseña
            if not user.check_password(password):
                raise forms.ValidationError('Contraseña incorrecta.')

        return super().clean()
    
    

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'email', 'phone', 'enable']  # Añade más campos si es necesario

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-user'}),
            'phone': forms.TextInput(attrs={'class': 'form-control form-control-user'}),

        }


    def clean(self):
        cleaned_data = super().clean()  # Guardar el resultado del super




class UpdateProfilePictureForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['avatar']  # Campo de la foto de perfil



User = get_user_model()

class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        # Verifica que las contraseñas coincidan
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        # Verifica la longitud mínima de la contraseña
        if password1 and len(password1) < 8:
            raise forms.ValidationError("La contraseña debe tener al menos 8 caracteres.")

        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este correo electrónico ya está en uso.")
        return email
class UpdateUserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'phone']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_phone(self):
        phone = self.cleaned_data['phone']

        # No necesitas esta validación si usas `phonefield`, ya que se encarga de validar
        # si any(char.isalpha() for char in str(phone)):
        #     raise forms.ValidationError("El número de teléfono no puede contener letras.")

        # Puedes hacer cualquier otra validación personalizada aquí, si lo deseas.

        return phone


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label="Nombre")

task_manager/apps/users/customers_api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from api.serializers import TaskSerializer, UserSerializer, CustomerSerializer
from apps.tasks.models import Task
from apps.users.models import User, Customer
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, action
from django.contrib.auth import authenticate
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.views import APIView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes
from apps.api.serializers import *
from dateutil import tz
from datetime import datetime

task_manager/apps/users/users_api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from api.serializers import TaskSerializer, UserSerializer, CustomerSerializer
from apps.tasks.models import Task
from apps.users.models import User, Customer
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, action
from django.contrib.auth import authenticate
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.views import APIView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes
from apps.api.serializers import *
from dateutil import tz
from datetime import datetime

task_manager/apps/users/templates/users/user_create.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block content %}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-flex align-items-center justify-content-center mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <!-- Create User Form -->
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Nuevo Usuario</h6>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.name.label_tag }}
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            {{ form.lastname.label_tag }}
                            {{ form.lastname }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            {{ form.phone.label_tag }}
                            {{ form.phone }}
                        </div>
                        <div class="form-group">
                            {{ form.avatar.label_tag }}
                            {{ form.avatar }}
                        </div>
                        <div class="form-group">
                            {{ form.groups.label_tag }}
                            {{ form.groups }}  <!-- Aquí se debe renderizar el select múltiple -->
                        </div>

                        <button type="submit" class="btn btn-primary btn-block">Crear Usuario</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/apps/users/templates/users/user_delete.html
ç{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-danger">Confirmación de Eliminación</h6>
        </div>
        <div class="card-body">
            <p>¿Estás seguro de que deseas eliminar al usuario <strong>{{ user.name }} {{ user.lastname }}</strong>?</p>
            <form method="POST">
                {% csrf_token %}
                <a href="{% url 'user_list' %}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/apps/users/templates/users/user_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Detalles del Usuario</h6>
        </div>
        <div class="card-body">
            <p><strong>Nombre:</strong> {{ user.name }}</p>
            <p><strong>Apellido:</strong> {{ user.lastname }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Teléfono:</strong> {{ user.phone }}</p>
            <p><strong>Foto:</strong></p>
            {% if user.photo %}
                <img src="{{ user.photo.url }}" alt="Foto de {{ user.name }}" class="img-fluid" style="max-width: 200px;">
            {% else %}
                <p>No hay foto disponible.</p>
            {% endif %}
            <a href="{% url 'user_list' %}" class="btn btn-secondary mt-3">Volver a la lista</a>
        </div>
    </div>
</div>
{% endblock %}

task_manager/apps/users/templates/users/user_detail_api.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Detalles del Usuario</h6>
        </div>
        <div class="card-body">
            <p id="#id_name"><strong >Nombre:</strong> {{ user.name }}</p>
            <p id="#id_lastname"><strong>Apellido:</strong> {{ user.lastname }}</p>
            <p id="#id_email"><strong>Email:</strong> {{ user.email }}</p>
            <p id="#id_phone"><strong>Teléfono:</strong> {{ user.phone }}</p>
            <p id="#id_avatar"><strong>Foto:</strong></p>
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Foto de {{ user.name }}" class="img-fluid" style="max-width: 200px;"><br>
            {% else %}
                <p>No hay foto disponible.</p>
            {% endif %}
            <a href="{% url 'user_list_api' %}" class="btn btn-secondary mt-3">Volver a la lista</a>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
     // Obtener el parámetro task_id de la URL

  const userId = {{pk}} // Esto obtiene el valor de task
  console.log(userId);

// script.js

// Función para obtener los detalles de la tarea
function getUserDetails(userId) {
  axios.get(`/api/v1/users/${taskId}/`) // Asegúrate de que esta URL sea la correcta
      .then(response => {
          const user = response.data;
          console.log(task)
          document.getElementById('id_name').innerText = user.name;
          document.getElementById('id_lastname').innerText = user.lastname;
          document.getElementById('id_email').innerText = user.email;
          document.getElementById('id_phone').innerText = user.phone;
          document.getElementById('id_avatar').innerText = user.avatar;
          document.getElementById('task-created-at').innerText = new Date(user.created_at).toLocaleString();
          document.getElementById('task-updated-at').innerText = new Date(user.updated_at).toLocaleString();
    

          // Si tienes permisos para editar y eliminar, añade la URL
          const editTaskLink = document.getElementById('edit-task');
          if (editTaskLink) {
              editTaskLink.href = `/tasks/edit/api/v1/?task_id=${taskId}`; // Ajusta la URL de edición según tu configuración de URL
          }

          const deleteTaskLink = document.getElementById('delete-task');
          if (deleteTaskLink) {
              deleteTaskLink.href = `/tasks/delete/?task_id=${taskId}`; // Ajusta la URL de eliminación según tu configuración de URL
          }
      })
      .catch(error => {
          console.error('Error al obtener los detalles de la tarea:', error);
          // Aquí puedes manejar el error, como mostrar un mensaje al usuario
      });
}

// Llamar a la función para obtener los detalles de la tarea
getUserDetails(userId);
</script>
{% endblock %}

task_manager/apps/users/templates/users/user_edit.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Editar Usuario</h6>
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
                <a href="{% url 'user_list' %}" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/apps/users/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
        <a href="{% url 'user_create' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Crear Nuevo Usuario
        </a>
    </div>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista de Usuarios</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Foto</th> <!-- Nueva columna para la foto -->
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Email</th>
                            <th>Teléfono</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>
                                {% if user.avatar %}
                                    <img src="{{ user.avatar.url }}" alt="Foto" width="50" height="50" onerror="this.src='{% static 'sb_admin_2/img/undraw_profile.svg' %}'">
                                {% else %}
                                    <img src="{% static 'sb-admin/img/undraw_profile.svg' %}" alt="Foto por defecto" width="50" height="50">
                                {% endif %}
                            </td>
                            {% if  user.enabled %}
                            <td>{{ user.name }}</td>
                            <td>{{ user.lastname }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.phone }}</td>
                            <td>
                                <a href="{% url 'user_detail' user.id %}" class="btn btn-info btn-circle btn-sm" title="Detalles">
                                    <i class="fas fa-info-circle"></i>
                                </a>
                                <a href="{% url 'user_edit' user.id %}" class="btn btn-warning btn-circle btn-sm" title="Editar">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="{% url 'user_delete' user.id %}" class="btn btn-danger btn-circle btn-sm" title="Eliminar">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </td>
                            {% else %}
                            <td style="text-decoration: line-through;">{{ user.name }}</td>
                            <td  style="text-decoration: line-through;">{{ user.lastname }}</td>
                            <td  style="text-decoration: line-through;">{{ user.email }}</td>
                            <td  style="text-decoration: line-through;">{{ user.phone }}</td>
                            <td>
                                <a href="{% url 'user_reactivate' user.id %}" class="btn btn-success btn-circle btn-sm" title="Eliminar">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">No hay usuarios registrados.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        {% if messages %}
            {% for message in messages %}
                Swal.fire({
                    title: '¡Atención!',
                    text: "{{ message }}",
                    icon: "{{ message.tags }}",
                    confirmButtonText: 'Aceptar'
                });
            {% endfor %}
        {% endif %}
    });
</script>
{% endblock %}